# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    source scripts/setup.sh || exit 1
    source scripts/setup_gae.sh || exit 1
  displayName: 'Setup environment.'

- script: |
    bash scripts/run_backend_tests.sh --generate_coverage_report
  displayName: 'Run backend tests.'
