# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.15-browsers

    working_directory: ~/foundation-website

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1.0-oppia-node-modules-cache-{{ checksum "package-lock.json"}}
      - restore_cache:
          keys:
            - v1.0-oppia-tools-cache-{{ checksum "oppia-tools-dependency-list.txt" }}
      - restore_cache:
          keys:
            - v1.0-oppia-pip-cache-{{ checksum "ci-linter-requirements.txt" }}

      - run:
          name: Run tests
          command: |
            bash scripts/run_backend_tests.sh --generate_coverage_report

      - run:
          name: Run linter
          command: |
            bash scripts/run_linter.sh

      - save_cache:
          key: v1.0-oppia-tools-cache-{{ checksum "oppia-tools-dependency-list.txt" }}
          paths:
            - ./oppia_tools/
      - save_cache:
          key: v1.0-oppia-node-modules-cache-{{ checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - save_cache:
          key: v1.0-oppia-pip-cache-{{ checksum "ci-linter-requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"
