# Configuration file for https://circleci.com/gh/oppia/foundation-website

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name`
# syntax dereferences it.
# See http://blog.daemonl.com/2016/02/yaml.html
# To validate changes, use an online parser, eg.
# http://yaml-online-parser.appspot.com/

# Variables

var_1: &docker_image circleci/python:2.7.15-browsers
var_2: &oppia_tools_cache_key oppia-tools-cache-{{ .Branch }}-{{ checksum "/tmp/oppia-tools-dependency-list.txt" }}-0.1.0
var_3: &oppia_node_modules_cache_key oppia-node-modules-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}-0.1.0

# Default settings for each job
anchor_1: &job_defaults
  working_directory: ~/foundation-website
  docker:
    - image: *docker_image

version: 2
jobs:
  backend_tests:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - *oppia_tools_cache_key

      - run:
          name: Run tests
          command: |
            bash scripts/run_backend_tests.sh --generate_coverage_report

      - save_cache:
          key: *oppia_tools_cache_key
          paths:
            - ./oppia_tools/
  linter:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - *oppia_node_modules_cache_key
            - *oppia_tools_cache_key

      - run:
          name: Run linter
          command: |
            bash scripts/run_linter.sh

      - run:
          # Generate a text file containing all dirs name within /oppia_tools
          name: Generate oppia_tools cache key
          command: |
            touch /tmp/oppia-tools-dependency-list.txt
            ls ~/foundation-website/oppia_tools > /tmp/oppia-tools-dependency-list.txt

      - save_cache:
          key: *oppia_node_modules_cache_key
          paths:
            - ./node_modules
      - save_cache:
          key: *oppia_tools_cache_key
          paths:
            - ./oppia_tools/

workflows:
  version: 2
  circleci_tasks:
    jobs:
      - backend_tests
      - linter
